<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
    <br />
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped1 By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking1 Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_shipment->getAllTracks() as $_item): ?>
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
